"use client";

import React from "react";
import { useParams } from "next/navigation";
import { Button } from "@/components/ui/button";

export default function SunlifeLoanMemo() {
  const { agentCode } = useParams();

  const agentDetails = {
    agentCode: agentCode || "Unknown",
    agentName: "Sunlife Agent Name",
    branch: "123",
    loanDate: "2024-01-01",
    interestRate: "7.5 %",
    loanDuration: "36 Months",
    loanAmount: "300,000.00",
  };

  return (
    <>
      {/* Print button fixed at top-right of viewport */}
      <div
        style={{
          position: "fixed",
          top: 20,
          right: 20,
          zIndex: 1000,
        }}
        className="no-print"
      >
        <Button onClick={() => window.print()} style={{ padding: "6px 12px" }}>
          Print
        </Button>
      </div>

      {/* Main content */}
      <div
        style={{
          maxWidth: 800,
          margin: "auto",
          padding: 24,
          background: "#f7f7f7",
          position: "relative",
        }}
      >
        <div className="flex flex-col items-center mb-6">
          <img
            src="/images/logo.png"
            alt="Sunlife Logo"
            className="rounded-xl h-20 w-auto mb-2"
          />
          <h1 className="text-2xl font-semibold">Agent Loan Memo</h1>
        </div>

        <hr />

        <h3 style={{ marginTop: 20, marginBottom: 10 }}>Loan Details</h3>

        <div style={{ display: "flex", justifyContent: "space-between" }}>
          <div>
            <strong>Branch.:</strong> {agentDetails.branch}
            <br />
            <strong>Agent Name.:</strong> {agentDetails.agentName}
            <br />
            <strong>Agent Code.:</strong> {agentDetails.agentCode}
            <br />
            <strong>Interest Rate.:</strong> {agentDetails.interestRate}
            <br />
            <strong>Loan Duration.:</strong> {agentDetails.loanDuration}
          </div>
          <div>
            <strong>Loan Date :-</strong> {agentDetails.loanDate}
          </div>
        </div>

        <p style={{ marginTop: 40, fontSize: 14, lineHeight: 1.6 }}>
          Re: Agent Loan Payment under{" "}
          <strong>
            Agent : {agentDetails.agentCode} / {agentDetails.agentName}
          </strong>{" "}
          has been eligible effective from date{" "}
          <strong>{agentDetails.loanDate}</strong> for{" "}
          <strong>{agentDetails.loanDuration}</strong> duration at{" "}
          <strong>{agentDetails.interestRate}</strong> interest rate.{" "}
          {agentDetails.agentName} requesting for agent loan along with
          necessity documents are hereby attached. On the basis of above memo, of{" "}
          <strong>Rs.{agentDetails.loanAmount}</strong> has been submitted for
          approval.
        </p>

        <div
          style={{
            marginTop: 60,
            display: "flex",
            justifyContent: "space-around",
          }}
        >
          <div style={{ textAlign: "center" }}>
            <hr style={{ width: 100 }} />
            <div>admin_user</div>
            <div>Prepared by</div>
          </div>

          <div style={{ textAlign: "center" }}>
            <hr style={{ width: 100 }} />
            <div>admin_user</div>
            <div>Checked by</div>
          </div>

          <div style={{ textAlign: "center" }}>
            <hr style={{ width: 100 }} />
            <div>Approved by</div>
          </div>
        </div>

        <div
          style={{
            textAlign: "center",
            marginTop: 80,
            fontSize: 12,
            color: "#666",
          }}
        >
          Generated By ADMIN_USER on {new Date().toLocaleString()}
        </div>
      </div>

      <style>
        {`
          @media print {
            .no-print {
              display: none !important;
            }
          }
        `}
      </style>
    </>
  );
}
